-- hey skidders
-- if you are browsing through the codes and wanted to copy them
-- please ask permission first then you can copy all of them
-- thank you

local Rayfield = loadstring(game:HttpGet('https://sirius.menu/rayfield'))()

local Window = Rayfield:CreateWindow({
   Name = "🍔 Mukbang Game Script 🍗",
   Icon = 0, -- Icon in Topbar. Can use Lucide Icons (string) or Roblox Image (number). 0 to use no icon (default).
   LoadingTitle = "Mukbang Game Script",
   LoadingSubtitle = "by blue25102558",
   ShowText = "Rayfield", -- for mobile users to unhide Rayfield, change if you'd like
   Theme = "AmberGlow", -- Check https://[Log in to view URL]

   ToggleUIKeybind = "K", -- The keybind to toggle the UI visibility (string like "K" or Enum.KeyCode)

   DisableRayfieldPrompts = false,
   DisableBuildWarnings = false, -- Prevents Rayfield from emitting warnings when the script has a version mismatch with the interface.

   -- ScriptID = "sid_xxxxxxxxxxxx", -- Your Script ID from developer.sirius.menu — enables analytics, managed keys, and script hosting

   ConfigurationSaving = {
      Enabled = false,
      FolderName = nil, -- Create a custom folder for your hub/game
      FileName = "funneh mukbang game script from blue25102558"
   },

   Discord = {
      Enabled = false, -- Prompt the user to join your Discord server if their executor supports it
      Invite = "noinvitelink", -- The Discord invite code, do not include Discord.gg/. E.g. Discord.gg/ABCD would be ABCD
      RememberJoins = true -- Set this to false to make them join the Discord every time they load it up
   },

   KeySystem = false, -- Set this to true to use our key system
   KeySettings = {
      Title = "Untitled",
      Subtitle = "Key System",
      Note = "No method of obtaining the key is provided", -- Use this to tell the user how to get a key
      FileName = "Key", -- It is recommended to use something unique, as other scripts using Rayfield may overwrite your key file
      SaveKey = true, -- The user's key will be saved, but if you change the key, they will be unable to use your script
      GrabKeyFromSite = false, -- If this is true, set Key below to the RAW site you would like Rayfield to get the key from
      Key = {"Hello"} -- List of keys that the system will accept, can be RAW file links (pastebin, github, etc.) or simple strings ("hello", "key22")
   }
})

    local MainTab = Window:CreateTab("🍗 Mukbangs", nil) -- Title, Image
    local Section = MainTab:CreateSection("🍗 Fried Chickens")

    Rayfield:Notify({
   Title = "Thanks for executing my script!",
   Content = "Lowkey tooked me around an hour to make this, but I hope you enjoy :)",
   Duration = 6.5,
   Image = nil,
})

    local Button = MainTab:CreateButton({
   Name = "Fried Chicken",
   Callback = function()
   -- The function that takes place when the button is pressed
            local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Fried Chicken"
    }
)
                
   end,
})

    local Button = MainTab:CreateButton({
   Name = "Flamin' Hot Chicken",
   Callback = function()
-- This code was generated by Cobalt
-- https://[Log in to view URL]

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Flamin' Hot Chicken"
    }
)

        end,
    })

    local Button = MainTab:CreateButton({
   Name = "Candied Chicken",
   Callback = function()
   -- The function that takes place when the button is pressed
            local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Candied Chicken"
    }
)
                
   end,
})

local Button = MainTab:CreateButton({
   Name = "Shallot Chicken",
   Callback = function()
            
local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Shallot Chicken"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Snowy Chicken",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Snowy Chicken"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Cheesy Snow Chicken",
   Callback = function()
   -- This code was generated by Cobalt
-- https://[Log in to view URL]

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cheesy Snow Chicken"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Spicy Honey Chicken",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Honey Chicken"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Honey Soy Chicken",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Honey Soy Chicken"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Takees Chicken",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Takees Chicken"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Blue Taki Chicken",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Blue Taki Chicken"
    }
)
   end,
})
local Section = MainTab:CreateSection("🧀 Cheesy")

local Button = MainTab:CreateButton({
   Name = "Baked Mac'n Cheese",
   Callback = function()
            
local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Baked Mac n Cheese"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Birria Tacos",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Birria Tacos"
    }
)
   end,
})

local Section = MainTab:CreateSection("🦞 Seafood Boil")

local Button = MainTab:CreateButton({
   Name = "Seafood Boil",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Seafood Boil"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Honey Seafood Boil",
   Callback = function()
   local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Honey Seafood Boil"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Spicy Seafood Boil",
   Callback = function()
   local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Seafood Boil"
    }
)
   end,
})

local Section = MainTab:CreateSection("🍔 Burger")

local Button = MainTab:CreateButton({
   Name = "Chicken Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Chicken Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Steak Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Steak Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Ham Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Ham Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Cheesy Chicken Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cheesy Chicken Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Cheesy Steak Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cheesy Steak Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Cheesy Ham Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cheesy Ham Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Mozzerella Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Mozzerella Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Tozzerella Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tozzerella Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Bozzerella Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Bozzerella Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Breakfast Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Breakfast Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Mozzilla Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Mozzilla Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Big Chicken Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Big Chicken Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Big Steak Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Big Steak Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Big Ham Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Big Ham Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Just Ham Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Just Ham Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Flamin Hot Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Flamin Hot Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Takees Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Takees Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Blue Taki Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Blue Taki Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Cookies N Cream Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cookies N Cream Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Matcha Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Matcha Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Strawberry Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Strawberry Burger"
    }
)
   end,
})

local RamenTab = Window:CreateTab("🍜 Ramen and Tteokbokki", nil) -- Title, Image
local Section = RamenTab:CreateSection("🍜 Ramen")

local Button = RamenTab:CreateButton({
   Name = "Carbonara",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Carbonara"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Spicy",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "2x Spicy",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Spicy"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Sardines",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Sardines"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Dumplings",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Dumplings"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Chicken Tenders",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Chicken Tenders"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Spam",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spam"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Sausage",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Sausage"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Eggs",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Eggs"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Tempura",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tempura"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Corn Cheese",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Corn Cheese"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Salmon",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon"
    }
)
   end,
})


local Button = RamenTab:CreateButton({
   Name = "Roe",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Roe"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Salmon Roe",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Roe"
    }
)
   end,
})

local Section = RamenTab:CreateSection("🍜 Tteokbokki")

local Button = RamenTab:CreateButton({
   Name = "Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Spicy Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "2x Spicy Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Spicy Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Jjajang Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Jjajang Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Curry Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Curry Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Sweet n Spicy Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Sweet n Spicy Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Cream Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cream Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Green Curry Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Green Curry Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Onion Butter Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Onion Butter Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Kimchi Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Kimchi Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Sausage Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Sausage Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Fish Cake Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Fish Cake Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Cheesy Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cheesy Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Eggs Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Eggs Tteokbokki"
    }
)
   end,
})

local Button = RamenTab:CreateButton({
   Name = "Flamin Hot Puff Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Flamin Hot Puff Tteokbokki"
    }
)
   end,
})

local SushiTab = Window:CreateTab("🍣 Sushi Menu", nil) -- Title, Image
local Section = SushiTab:CreateSection("🍣 Salmon")

local Button = SushiTab:CreateButton({
   Name = "Salmon Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Salmon Roe Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Roe Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "2x Salmon Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Salmon Maki"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Tuna")

local Button = SushiTab:CreateButton({
   Name = "Tuna Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tuna Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Tuna Roe Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tuna Roe Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "2x Tuna Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Tuna Maki"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Trout")

local Button = SushiTab:CreateButton({
   Name = "Trout Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Trout Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Trout Roe Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Trout Roe Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "2x Trout Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Trout Maki"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Kojac")

local Button = SushiTab:CreateButton({
   Name = "Kojac Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Kojac Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "2x Kojac Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Kojac Maki"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Usuzukuri")

local Button = SushiTab:CreateButton({
   Name = "Usuzukuri Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Usuzukuri Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Usuzukuri Roe Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Usuzukuri Roe Maki"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Salmon Crunch")

local Button = SushiTab:CreateButton({
   Name = "Salmon Crunch Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Crunch Maki"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Octopus")

local Button = SushiTab:CreateButton({
   Name = "Octopus Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Octopus Maki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Spicy Octopus Maki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Octopus Maki"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍕 Sushi Pizzas")

local Button = SushiTab:CreateButton({
   Name = "Salmon Pizza",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Pizza"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Tuna Pizza",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tuna Pizza"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Usuzukuri Pizza",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Usuzukuri Pizza"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🌮 Sushi Tacos")

local Button = SushiTab:CreateButton({
   Name = "Sushi Taco",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Sushi Taco"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Tuna Taco",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tuna Taco"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Salmon Taco",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Taco"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Sushi Sticks")

local Button = SushiTab:CreateButton({
   Name = "Salmon Stick",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Stick"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Tuna Stick",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tuna Stick"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Seabass Stick",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Seabass Stick"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Yellowtail Stick",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Yellowtail Stick"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Usuzukuri Stick",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Usuzukuri Stick"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 Sushi Slabs")

local Button = SushiTab:CreateButton({
   Name = "Salmon Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Tuna Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tuna Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Yellowtail Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Yellowtail Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Kohada Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Kohada Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Seabass Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Seabass Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Organic Usuzukuri Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Organic Usuzukuri Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Flounder Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Flounder Slab"
    }
)
   end,
})

local Section = SushiTab:CreateSection("🍣 King Tentacles")

local Button = SushiTab:CreateButton({
   Name = "Spicy King Tentacle",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy King Tentacle"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "King Tentacle",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "King Tentacle"
    }
)
   end,
})

local DrinkTab = Window:CreateTab("🍺 Drinks", nil) -- Title, Image
local Section = DrinkTab:CreateSection("🍺 Drinks")

local Button = DrinkTab:CreateButton({
   Name = "Water",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Water"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Apple Juice",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Apple Juice"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Cola",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cola"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Orange Soda",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Orange Soda"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Lime Soda",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Lime Soda"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Lemon Soda",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Lemon Soda"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Grapefruit Soda",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Grapefruit Soda"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Milk",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Milk"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Strawberry Milk",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Strawberry Milk"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Choco Milk",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Choco Milk"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Banana Milk",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Banana Milk"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Blueberry Milk",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Blueberry Milk"
    }
)
   end,
})

local Button = DrinkTab:CreateButton({
   Name = "Matcha Milk",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Matcha Milk"
    }
)
   end,
})

local SnacksTab = Window:CreateTab("🍡 Snacks", nil) -- Title, Image
local Section = SnacksTab:CreateSection("🍡 Corn Dogs")

local Button = SnacksTab:CreateButton({
   Name = "Corn Dog",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Corn Dog"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Crumble Dog",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Crumble Dog"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Panko Dog",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Panko Dog"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Apple Cubu Dog",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Apple Cubu Dog"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Flamin' Hot Dog",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Flamin' Hot Dog"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Takees Dog",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Takees Dog"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Blue Taki Dog",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Blue Taki Dog"
    }
)
   end,
})

local Section = SnacksTab:CreateSection("🍢 Sticks")

local Button = SnacksTab:CreateButton({
   Name = "Mozzarella Sticks",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Mozzarella Sticks"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Takis Mozzarella",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Takis Mozzarella"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Blue Taki Mozzarella",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Blue Taki Mozzarella"
    }
)
   end,
})

local Section = SnacksTab:CreateSection("🧅 Boils")

local Button = SnacksTab:CreateButton({
   Name = "Onion Boil",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Onion Boil"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Sea Grapes",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Sea Grapes"
    }
)
   end,
})

local Section = SnacksTab:CreateSection("🍡 Enokis")

local Button = SnacksTab:CreateButton({
   Name = "Spicy Enoki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Enoki"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Blackbean Enoki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Blackbean Enoki"
    }
)
   end,
})

local Section = SnacksTab:CreateSection("🍢 Mussels")

local Button = SnacksTab:CreateButton({
   Name = "Mussels",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Mussels"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Honey Mussels",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Honey Mussels"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Spicy Mussels",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Mussels"
    }
)
   end,
})

local Section = SnacksTab:CreateSection("🦞 Lobster Tails")

local Button = SnacksTab:CreateButton({
   Name = "Lobster Tails",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Lobster Tails"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Honey Lobster Tails",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Honey Lobster Tails"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Spicy Lobster Tails",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Lobster Tails"
    }
)
   end,
})

local Section = SnacksTab:CreateSection("🦀 Crab Claws")

local Button = SnacksTab:CreateButton({
   Name = "Crab Claws",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Crab Claws"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Honey Crab Claws",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Honey Crab Claws"
    }
)
   end,
})

local Button = SnacksTab:CreateButton({
   Name = "Spicy Crab Claws",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Crab Claws"
    }
)
   end,
})

local DessertsTab = Window:CreateTab("🍨 Desserts", nil) -- Title, Image
local Section = DessertsTab:CreateSection("🥣 Cereals")

local Button = DessertsTab:CreateButton({
   Name = "Choco Buttons Cereal",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Choco Buttons Cereal"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Chocoballs Cereal",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Chocoballs Cereal"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Cookies n Cream Cereal",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cookies n Cream Cereal"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Strawberry Cookie Cereal",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Strawberry Cookie Cereal"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Matcha Cookie Cereal",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Matcha Cookie Cereal"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Macaron Cereal",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Macaron Cereal"
    }
)
   end,
})

local Section = DessertsTab:CreateSection("🍪 Chewy Cookies")

local Button = DessertsTab:CreateButton({
   Name = "Matcha Chewy Cookie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Matcha Chewy Cookie"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Dubai Chewy Cookie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Dubai Chewy Cookie"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Biscuit Chewy Cookie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Biscuit Chewy Cookie"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Strawberry Chewy Cookie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Strawberry Chewy Cookie"
    }
)
   end,
})

local Section = DessertsTab:CreateSection("🥧 Pies")

local Button = DessertsTab:CreateButton({
   Name = "Apple Pie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Apple Pie"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Blueberry Pie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Blueberry Pie"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Strawberry Pie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Strawberry Pie"
    }
)
   end,
})

local Section = DessertsTab:CreateSection("🍫 Brownies")

local Button = DessertsTab:CreateButton({
   Name = "Welldone Brownie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Welldone Brownie"
    }
)
   end,
})

local Section = DessertsTab:CreateSection("🍲 Gooey")

local Button = DessertsTab:CreateButton({
   Name = "Gooey Brownie",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Brownie"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Gooey Velvet",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Velvet"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Gooey Dubai",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Dubai"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Gooey Vanilla",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Vanilla"
    }
)
   end,
})

local SauceTab = Window:CreateTab("🍲 Sauce", nil) -- Title, Image
local Section = SauceTab:CreateSection("🍲 Sauce")

local Button = SauceTab:CreateButton({
   Name = "Cheese",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Cheese"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Spicy",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Spicy"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Mayo",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Mayo"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Sweet n' Sour",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Sweet n Sour"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Ranch",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Ranch"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Birria",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Birria"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Onion Powder",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Onion Powder"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Honey Garlic",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Honey Garlic"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Honey Mustard",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Honey Mustard"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Cajun",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Cajun"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Ponzu",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Ponzu"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Wasabi",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Wasabi"
    }
)
   end,
})

local Button = SauceTab:CreateButton({
   Name = "Spicy Mayo",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceSauceOrder
Event:FireServer(
    {
        "Spicy Mayo"
    }
)
   end,
})


local MiscTab = Window:CreateTab("❔ Misc", nil) -- Title, Image
local Section = MiscTab:CreateSection("⭐ Features")

local infBitesEnabled = false
local infBitesConnection = nil

MiscTab:CreateToggle({
    Name = "Infinite Bites",
    CurrentValue = false,
    Callback = function(state)
        infBitesEnabled = state
        if infBitesConnection then infBitesConnection:Disconnect() infBitesConnection = nil end
        if state then
            infBitesConnection = game:GetService("RunService").Heartbeat:Connect(function()
                if not infBitesEnabled then return end
                pcall(function()
                    for i = 1, 3 do
                        local args = {{ Bite = 1, Noodletype = "Carbonara", Action = "Bite", Tool = game:GetService("Players").LocalPlayer.Character:WaitForChild("Carbonara"), FoodType = "SkilletNoodles" }}
                        game:GetService("ReplicatedStorage"):WaitForChild("NoodlesSkilletEvent"):FireServer(unpack(args))
                    end
                end)
                task.wait(0.0001)
            end)
        end
    end
})

MiscTab:CreateButton({
    Name = "Steps (Teleport + Order)",
    Callback = function()
        local plr = game:GetService("Players").LocalPlayer
        local char = plr.Character or plr.CharacterAdded:Wait()
        local hrp = char:WaitForChild("HumanoidRootPart")
        hrp.CFrame = CFrame.new(8.23, 2.72, -3.85)
        task.wait(1)
        local args = {{"Carbonara"}}
        game:GetService("ReplicatedStorage"):WaitForChild("PlaceFoodOrder"):FireServer(unpack(args))
        game.StarterGui:SetCore("SendNotification", { Title = "Steps", Text = "Place Food and collect The Food", Duration = 8 })
    end
})

local Section = MiscTab:CreateSection("⭐ All Gamepass Foods")

local Button = MiscTab:CreateButton({
   Name = "Seafood Boil",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Seafood Boil"
    }
)
   end,
})

local Button = MiscTab:CreateButton({
   Name = "Honey Seafood Boil",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Honey Seafood Boil"
    }
)
   end,
})

local Button = MiscTab:CreateButton({
   Name = "Spicy Seafood Boil",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy Seafood Boil"
    }
)
   end,
})

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Cookies N Cream Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Matcha Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Matcha Burger"
    }
)
   end,
})

local Button = MainTab:CreateButton({
   Name = "Strawberry Burger",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Strawberry Burger"
    }
)
   end,
})

local Button = MiscTab:CreateButton({
   Name = "2x Spicy",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Spicy"
    }
)
   end,
})

local Button = MiscTab:CreateButton({
   Name = "2x Spicy Tteokbokki",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "2x Spicy Tteokbokki"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Salmon Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Salmon Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Tuna Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Tuna Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Yellowtail Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Yellowtail Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Kohada Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Kohada Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Seabass Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Seabass Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Organic Usuzukuri Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Organic Usuzukuri Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Flounder Slab",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Flounder Slab"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "Spicy King Tentacle",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Spicy King Tentacle"
    }
)
   end,
})

local Button = SushiTab:CreateButton({
   Name = "King Tentacle",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "King Tentacle"
    }
)
   end,
})

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Brownie"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Gooey Velvet",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Velvet"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Gooey Dubai",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Dubai"
    }
)
   end,
})

local Button = DessertsTab:CreateButton({
   Name = "Gooey Vanilla",
   Callback = function()

local Event = game:GetService("ReplicatedStorage").PlaceFoodOrder
Event:FireServer(
    {
        "Gooey Vanilla"
    }
)
   end,
})

MiscTab:CreateLabel("ROBLOX: blue25102558")

MiscTab:CreateLabel("YouTube: fourisanaverageguy")

Rayfield:Notify({Title = "Infinite bites loaded!", Content = "All tabs + features ready!", Duration = 5})
